### ISSUE TITLE
License has been removed

### ISSUE THREAD

**Issue by IainNZ** [wheatman/A-Tour-Around-US-National-Parks-A-Modified-TSP#1]
Hello,
It has come to my attention that you have taken the JuMP TSP example, which I wrote, made minor modifications, and stripped the license header (and used it in a class project).
Please restore the JuMP license and provide proper attribution.

CC: @mlubin, @joehuchette

**Comment by wheatman** [comment]
I am sorry about that.  I will do that right away.  For the turned in
portion they asked that we attribute it, but not include the header itself
and I forgot to add it back when  it got uploaded.

**Comment by wheatman** [comment]
I believe it should be fixed now.  I apologize again for the issue, I did not review the code in between turning in the project.  The attribution was only included in the paper and not in the code itself.  Let me know if I did not include the license properly.

**Comment by IainNZ** [comment]
Thanks!
